### PR TITLE
Add PID to rpc response queue

### PR DESCRIPTION
**Pull request by yosiat**
So we can have multiple processes on the same machine sending RPC to same service and not get RESOURCE_LOCKED

### CODE REVIEW

**Review by mrister — APPROVED** [review]

**Review by ykhatal — APPROVED** [review]

**Comment by ykhatal** [comment]
@yosiat thanks for the contribution

**Comment by yosiat** [comment]
@ky23 happy to contribute!

**Review by Spring3 — APPROVED** [review]

**Comment by rafaismyname** [comment]
Great contrib!
I used to have dynamic hostnames with the PID concatenated to it to avoid those resource locks.
But this looks like the real deal! ;)

Thanks

**Comment by yosiat** [comment]
Can we merge this and release a version?

**Pull request merged**
