### PR TITLE
Bugfix/fix channel close

### LINKED ISSUE #48: Channel is closed when trying to send to a queue that is not existing
This is behaviour of amqp.node however we want to allow it to bubble up error but keep channel opened, as we mutualise channels between bunnymq instances.

Error printed in console:

```
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668547588Z { Error: Channel ended, no reply will be forthcoming
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668585994Z     at rej (/usr/src/app/node_modules/amqplib/lib/channel.js:190:7)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668593403Z     at Channel.C._rejectPending (/usr/src/app/node_modules/amqplib/lib/channel.js:196:42)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668598579Z     at Channel.C.toClosed (/usr/src/app/node_modules/amqplib/lib/channel.js:160:8)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668603493Z     at Channel.C.accept (/usr/src/app/node_modules/amqplib/lib/channel.js:411:10)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668608713Z     at Connection.mainAccept [as accept] (/usr/src/app/node_modules/amqplib/lib/connection.js:63:33)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668614323Z     at Socket.go (/usr/src/app/node_modules/amqplib/lib/connection.js:476:48)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668632611Z     at emitNone (events.js:86:13)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668637260Z     at Socket.emit (events.js:185:7)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668642165Z     at emitReadable_ (_stream_readable.js:438:10)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668646766Z     at emitReadable (_stream_readable.js:432:7)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668651371Z     at readableAddChunk (_stream_readable.js:183:13)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668655986Z     at Socket.Readable.push (_stream_readable.js:130:10)
gateway-socket-eu-central-2 | 2016-08-03T10:23:33.668660523Z     at TCP.onread (net.js:542:20) type: 'no_queue' }
```

### PR DESCRIPTION
**Pull request by mrister**
Closes #48 

Since checkChannel closes a channel if queue does not exist, this will create it again.
Augmented tests to see if this problem is fixed.

### CODE REVIEW

**Comment by ykhatal** [comment]
LGTM

**Comment by PuKoren** [comment]
I think it would be very time consuming to recreate the channel every time a message is sent to a non-existing queue

The `channel.checkQueue` method isn't supposed to check it before trying to send the message and triggering the error + internal server close? If `channel.checkQueue` triggers a channel close, we should find another way: maybe opening a channel/queue? I don't like it much, but it would solve #43. Can you take a look at AMQP protocol recommandations? I think they say 1 channel/thread, and since nodejs and since we run in a non-fork mode, multiple channel may be bad

BTW, something weird happened on the branch there is a lot of merge commits, did you start the branch from master?

**Comment by jkernech** [comment]
Indeed something weird happened there, the commit history is quite messy... 

Following @PuKoren comment, we need to investigate further the AMQP protocol recommendations and most importantly make sure how we can make things work with a mono-threaded app (since we don't cluster our nodejs app...). Once things are clarified, I propose we enhance the development guidelines to mention this, it will be useful in the future

**Comment by mrister** [comment]
Sorry for messing up the PR, I'll rebase it correctly tomorrow morning.

So the problem here is that the checkChannel closes the channel if it does not exist. I read about it quite extensively and been all over amqplib code. There is a possible workaround that could be tested wich passing passive:true|false params to assertQueue or checkQueue (which involves a slight performance hit). But amqplib (looking at the code) manipulates those on its own and does not allow (nor document) them. So only recreating the channel here helped.

@PuKoren I think the  recreate happens only on producer.produce as the error about not existing. Since I don't have the ability to stop broker from closing the channel, I don't know what else to do.

I'll take a look at the specs and see what we could maybe do with passive flag but we may be blocked by underlying amqplib on doing so.

Or we need to find an alternate way to check if queue exists. Which I don't know how to do either.

Any suggestions are more than welcome.

Adding this:
Seems there is an API that might be used to check queues, but requires a rabbitmq plugin
http://hg.rabbitmq.com/rabbitmq-management/raw-file/3646dee55e02/priv/www-api/help.html
http://grokbase.com/t/rabbitmq/rabbitmq-discuss/108bs4r7g5/queue-exists-or-not

**Comment by PuKoren** [comment]
@mrister thanks for the update, you made it clear.
I will dig into the code too so we can discuss it more in-depth, I hope we can find a solution that is both performant and reliable

**Comment by PuKoren** [comment]
@mrister I read a lot the AMQP protocol and best practices. 

I also checked a recently added feature that is not working (fix in progress) and maybe we wanted to do something that is not AMQP-friendly.

Basically, a queue should exists or be created when you send a message to it, and you can use the routing keys to forward the message to the correct backend.

Sample pseudocode:

``` js
amqp.subscribe('my-queue', { routingKeys: ['apples', 'bananas'] });

amqp.publish('my-queue', { routingKey: 'apples' }); //will be received
amqp.publish('my-queue', { routingKey: 'bananas' }); //will be received
amqp.publish('my-queue', { routingKey: 'oranges' }); //will be discarded
```

This way, we can have multiple services registered to one queue, but the message is forwarded to a different service based on the routing key, or discarded.

This seems to be the current AMQP recommandations: 
https://github.com/squaremo/amqp.node/blob/30a346bc83f863c829324fb26be142d019018dd6/examples/tutorials/receive_logs.js
https://www.rabbitmq.com/tutorials/tutorial-four-javascript.html

And it suits to original use case for this scenario: ability to send to a non-existing service. So maybe the feature was already there? What do you think about it?

I think it will be a very tough one as we will need to handle exchanges, and that is not done yet. And it will cause some issue in the current module architecture to handle this with RPC.

**Comment by mrister** [comment]
@PuKoren maybe you are onto something, needs testing but perhaps it would work. It is possible that non existent exchanges have the same effect on closing the channel ( I think I read about it). Worth trying out to see if it helps for sure!

**Comment by PuKoren** [comment]
@mrister you are right:

> #publish(exchange, routingKey, content, [options])
> exchange and routingKey: the exchange and routing key, which determine where the message goes. A special case is sending '' as the exchange, which will send directly to the queue named by the routing key; #sendToQueue below is equivalent to this special case. If the named exchange does not exist, the channel will be closed.

So if we want to do this, we have to specify an existing exchange.

I guess 

```
amqp.produce('', { object }, { routingKey: 'my-non-existing-route' });
```

would work. But we still have to manage the exchanges correctly. [My work in progress here](https://github.com/dial-once/node-bunnymq/tree/feature/routing-keys-exchanges)

**Comment by PuKoren** [comment]
@mrister for now, I suggest that we rollback the module to cancel the feature as it differs too much from AMQP and amqp.node specs, and this results on a bad general behaviour when using the feature (closing/reopening channel: it creates a close handshake and an open handshake, on high i/o systems this may cause serious issues, and on low i/o this may lead to bad behaviour with re-queues)

Considering base issue (send a message using RPC on a maybe non-existing queue), we could achieve the thing on the previous version of the module, but we need to clean pending RPC callbacks (with a timeout setting maybe?) as described on #45. I'm afraid we have no way to know if a queue exists or not without causing the channel to be closed.

Developing exchanges and routing keys completely will be too early in the module life as it is still pretty much basic and not entirely cleaned up

**Comment by PuKoren** [comment]
I added the feature + channel check revert on this branch: https://github.com/dial-once/node-bunnymq/tree/feature/rpc-timeout

There is also a test that check if the timeout is called. I will let you guys discuss about it next week, I think it should solve the feature that we wanted initially and allow us to delay the dev of the complex exchange/routing key feature.

Documentation is missing, here is how to use it:

``` js
      return producer.produce('non-existing-queue', { msg: 'ok' }, { rpc: true, timeout: 1000 })
        .catch((e) => {
            //is triggered after 1000ms
        });
```

Garbage collector should clean the functions declared in the `.then` sections.

About the feature added in 2.2 and reverted (if you chose to merge my PR), I let you chose between bumping to 3.0 or ninja-ing the version.

**Comment by mrister** [comment]
@PuKoren Your fix seems to work ok. I'm still testing for a roundtrip (will let you know)  for grdf example (from screen engine to grdf queue and back)

**Comment by mrister** [comment]
@jkernech @PuKoren  I completed testing and this works on in/out services (GRDF)! we just need small adjustments (when Jonathan's fix gets merged in) in gateway-socket events.js (processHooks) to check for timeout error and not use err.type=no_queue. Gr8 work @PuKoren !!

**Comment by jkernech** [comment]
Great work @PuKoren @mrister !!

Still need some functional testing but so far LGTM

**Comment by mrister** [comment]
@jkernech @PuKoren  So are we going to merge jonathan's Pr? What abou bunny version then ? And we can then close and discard this one ?

**Comment by PuKoren** [comment]
I vote to bump the version as a patch as it concern the initial feature request, even if it is a breaking change (it's a bit dirty but it will avoid some headache and I think no one is using the released feature about non-existing channel)

**Comment by mrister** [comment]
I second @PuKoren 's patch proposal fully :-)

**Pull request closed without merging**
